import { Exercise } from '@gym-tracker/types';

const at = (name: string, muscleGroup: any, equipment: any, exerciseType: any = 'weight_reps', extra: Partial<Exercise> = {}): Exercise => ({
  id: `lib-${name.toLowerCase().replace(/[^a-z0-9]+/g, '-')}`,
  name,
  muscleGroup,
  equipment,
  exerciseType,
  createdAt: '2024-01-01T00:00:00.000Z',
  ...extra,
});

/** Bundled exercise library so guests can train offline without an account. */
export const GUEST_EXERCISE_LIBRARY: Exercise[] = [
  at('Barbell Bench Press', 'chest', 'barbell'),
  at('Incline Barbell Bench Press', 'chest', 'barbell'),
  at('Dumbbell Bench Press', 'chest', 'dumbbell'),
  at('Incline Dumbbell Press', 'chest', 'dumbbell'),
  at('Cable Fly', 'chest', 'cable'),
  at('Pec Deck', 'chest', 'machine'),
  at('Deadlift', 'back', 'barbell'),
  at('Barbell Row', 'back', 'barbell'),
  at('Seated Cable Row', 'back', 'cable'),
  at('Lat Pulldown', 'back', 'cable'),
  at('Pull-Up', 'back', 'bodyweight', 'bodyweight_reps'),
  at('Chin-Up', 'back', 'bodyweight', 'bodyweight_reps'),
  at('Single Arm Dumbbell Row', 'back', 'dumbbell'),
  at('Overhead Press', 'shoulders', 'barbell'),
  at('Dumbbell Shoulder Press', 'shoulders', 'dumbbell'),
  at('Lateral Raise', 'shoulders', 'dumbbell'),
  at('Rear Delt Fly', 'shoulders', 'dumbbell'),
  at('Face Pull', 'shoulders', 'cable'),
  at('Barbell Back Squat', 'legs', 'barbell'),
  at('Front Squat', 'legs', 'barbell'),
  at('Leg Press', 'legs', 'machine'),
  at('Romanian Deadlift', 'legs', 'barbell'),
  at('Leg Curl', 'legs', 'machine'),
  at('Leg Extension', 'legs', 'machine'),
  at('Bulgarian Split Squat', 'legs', 'dumbbell'),
  at('Walking Lunges', 'legs', 'dumbbell'),
  at('Calf Raise', 'legs', 'machine'),
  at('Barbell Curl', 'arms', 'barbell'),
  at('Dumbbell Curl', 'arms', 'dumbbell'),
  at('Hammer Curl', 'arms', 'dumbbell'),
  at('Preacher Curl', 'arms', 'barbell'),
  at('Tricep Pushdown', 'arms', 'cable'),
  at('Skull Crusher', 'arms', 'barbell'),
  at('Overhead Tricep Extension', 'arms', 'dumbbell'),
  at('Dips', 'arms', 'bodyweight', 'bodyweight_reps'),
];
